# This is a basic workflow to help you get started with Actions

name: Check Day

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: "15 2 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      # Set up Python '3.10' 
      - name: Set up Python '3.10' 
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
      - name: Display Python version
        run: |
          # output=$(python Test.py)
          # output="${output//'%'/'%25'}"
          # output="${output//$'\n'}"
          # output="${output//$'\r'/'%0D'}" 
          # echo "::set-output name=changelog::$output"
          echo "changelog=$output" >> $GITHUB_OUTPUT
        id: step1
      - name: Print changelog
        run: echo "${{ steps.step1.outputs.changelog }}"
